yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/', views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/', views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу поста'
    )

    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
        help_text='Вы можете загружить картинку к посту'
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from xml.etree.ElementTree import Comment
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Группа не выбрана'

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow

NUMBER_OF_POSTS = 10


def index(request):
    template_name = 'posts/index.html'
    post_list = Post.objects.all().order_by('-created')
    paginator = Paginator(post_list, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


def group_posts(request, slug):
    template_name = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.all().filter(group=group)
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = 'Записи сообщества'
    context = {
        'group': group,
        'title': title + ' ' + str(group),
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


def profile(request, username):
    template_name = 'posts/profile.html'
    user_profile = get_object_or_404(User, username=username)
    user = request.user
    if user.is_authenticated:
        follow = Follow.objects.filter(
            user=user, author=user_profile
        )
        if user_profile != user and follow.exists():
            following = True
        else:
            following = False
    else:
        following = False
    user_posts = user_profile.posts.all()
    paginator = Paginator(user_posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_counter = user_posts.count()
    title = f'Профайл пользователя {user_profile.get_full_name()}'
    context = {
        'title': title,
        'author': user_profile,
        'page_obj': page_obj,
        'post_counter': post_counter,
        'following': following,
    }
    return render(request, template_name, context)


def post_detail(request, post_id):
    template_name = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_list = Post.objects.all()
    post_counter = post_list.filter(author=post.author).count()
    title = post.text[:30]
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'title': title,
        'post': post,
        'post_list': post_list,
        'post_counter': post_counter,
        'form': form,
        'comments': comments,
    }
    return render(request, template_name, context)


@login_required
def post_create(request):
    template_name = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'title': 'Создать новую запись',
        'form': form
    }
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author.username)
        return render(request, template_name, context)
    return render(request, template_name, context)


@login_required
def post_edit(request, post_id):
    template_name = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if request.user.id != post.author.id:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'title': 'Редактировать запись',
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, template_name, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template_name = 'posts/follow.html'
    user = request.user
    authors = Follow.objects.filter(user=user).values('author')
    posts = Post.objects.filter(author__in=authors)
    paginator = Paginator(posts, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template_name, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author)
    if request.user != author and not follow.exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=request.user,
        author=author)
    if request.user != author and follow.exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}           
              </div>
              <div class="card-body">        
                <form action="{{ request.get_full_path }}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}           
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{form.text.label}}               
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}               
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{form.group.label}}                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      {{form.image.label}}                      
                    </label>
                    {% if is_edit %}
                      {% if post.image.url != NULL %}
                      На данный момент:
                        <a href="{{post.image.url}}">Открыть картинку</a>
                        <input type="checkbox" name="image-clear" id="image-clear_id">
                        <label for="image-clear_id">Очистить</label><br>
                      {% endif %}
                      Изменить:
                      <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                    {% else %}
                      <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                    {% endif %}                      
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Лента{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 index_page page_obj.number %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
          {% if post.group_id != NULL %}
            <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
          {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  </div>
{% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container py-5">
    <h1> {%block header%} {{group.title}} {%endblock%} </h1>
    <p> {{ group.description}} </p>
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  </div>
{% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% cache 20 post page_obj.number %}
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
          {% if post.group_id != NULL %}
            <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
          {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endcache %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html'%}
    {% block content %}
      {% load thumbnail %}    
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.created|date:"d E Y" }}
            </li>
            {% if post.group_id != NULL %}   
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  Все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{post.author.get_full_name}}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_counter }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                  Все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" padding=True upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text }}
          </p>
          {% if post.author.username == user.username %}
          <a class="btn btn-primary" href={% url 'posts:post_edit' post.id %}>
            Редактировать запись
          </a>
          {% endif %}
          {% include 'posts/includes/comment.html'%}
        </article>
      </div> 
    {% endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{%block content%}
{% load thumbnail %}
      <div class="container py-5">       
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ post_counter }} </h3>
        {% if user.is_authenticated %} 
          {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
          {% else %}
            {% if author != request.user %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
            {% endif %}
          {% endif %}
        {% endif %}
        {% for post in page_obj %}   
        {% include 'posts/includes/post.html' %}
        {% if post.group_id != NULL %}       
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
        {% endif %}        
        <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %} 
      </div>
{% endblock %}